//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.25 at 08:13:03 PM KST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/sqlmap", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package springbook.user.sqlservice.jaxb;
